/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *acceuil;
  GtkWidget *ajout;
  GtkWidget *supprimer;
  GtkWidget *Recherche;
  GtkWidget *Modification;
  GtkWidget *affiche;
  GtkWidget *enregistrement;
  GtkWidget *attention;
  GtkWidget *dashboard;


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  acceuil = create_acceuil ();
  gtk_widget_show (acceuil);

  /*ajout = create_ajout ();
  gtk_widget_show (ajout);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  Recherche = create_Recherche ();
  gtk_widget_show (Recherche);
  Modification = create_Modification ();
  gtk_widget_show (Modification);
  affiche = create_affiche ();
  gtk_widget_show (affiche);
  enregistrement = create_enregistrement ();
  gtk_widget_show (enregistrement);
  attention = create_attention ();
  gtk_widget_show (attention);
  dashboard = create_dashboard ();
  gtk_widget_show (dashboard);*/

  gtk_main ();
  return 0;
}

